### ISSUE TITLE
SCSS sourcemaps are included in the build

### ISSUE THREAD

**Issue by Markovnin** [preactjs-templates/widget#11]
By default, `npm run build` will leave SCSS source maps in the build code (see attached image). Is there a way to disabled it? Source maps are not needed in the build.

<img width="941" alt="0gSkK" src="https://user-images.githubusercontent.com/37826/65957134-c7ae8580-e454-11e9-815e-08795cabb7a7.png">

**Comment by ForsakenHarmony** [comment]
This might be fixed in the newest `preact-cli` rc, but not entirely sure if this template is compatible
