### ISSUE TITLE
Not use node-SASS?

### ISSUE THREAD

**Issue by tomByrer** [preactjs-templates/widget#12]
```bash
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
```
Win10, which is likely why it fails.  & I'm not really interested in jumping though hoops to add SASS rendering I'm not going to use.

### Fix options

 * switch to (Dart) `sass`, which is actually the [official SASS](https://sass-lang.com/dart-sass), though slightly slower, node-sass is not 100% API parity.  I switched popular [Video.js](https://github.com/videojs/video.js/blob/master/package.json#L140) a year ago & still seems to work for them.
 * Warn & allow to bail `node-sass` is about to be compiled in CLI
 * Note in both READMEs that `widget` includes node-sass
 * Maintain a plain CSS fork.

cheers :)

**Comment by pm0u** [comment]
is there a workaround for this? i have no interest in using sass and this kills any chance of me using the widget template

**Comment by pm0u** [comment]
got it - remove reference to any .scss files, and you can safely remove node-sass and sass-loader from package.json :+1:

**Comment by ForsakenHarmony** [comment]
The template now just uses plain css

**Comment by ForsakenHarmony** [comment]
@tomByrer if there's a blocker in preact-cli which prevents you from using dart-sass, feel free to submit a PR to `preact-cli`
