### ISSUE TITLE
Disable extracting CSS into separate file on latest preact-cli (v3.0.5)

### ISSUE THREAD

**Issue by billdami** [preactjs-templates/widget#15]
It appears preact-cli has switched from ExtractTextPlugin to MiniCssExtractPlugin in newer releases for extracting the build's CSS into a separate file, which obviously causes this in the `preact.config.js` file to fail:

```js
let { plugin } = helpers.getPluginsByName(config, "ExtractTextPlugin")[0];
plugin.options.disable = true;
```

I didn't see any option in the MiniCssExtractPlugin config that allows it to be completely disabled, is there another way of doing this?

**Comment by ForsakenHarmony** [comment]
I suppose one way would be to remove the plugin/loader entirely from the config 🤔

**Comment by billdami** [comment]
@ForsakenHarmony thanks for the reply, though I ended up going with a different forked template for my needs. Out of curiosity, whats the best way to remove the plugin/loader from the config, since the config itself is baked into preact-cli? Is there APIs for doing that?

**Comment by ForsakenHarmony** [comment]
There isn't, you'd have to get the plugin and then splice it from the plugins array
