### ISSUE TITLE
Build template.html and copy into the dist/

### ISSUE THREAD

**Issue by NomeQ** [preactjs-templates/widget#17]
It would be nice to have the `template.html` built without the `<% preact %>` tags and included in the build folder. It doesn't look like microbundle makes it easy to pass in any arguments to do so.

Even though this template is meant to be used for embeddable and reusable widgets, it's handy to have a basic static html file for demo purposes, and for checking the build output.

**Comment by rschristian** [comment]
The template is strictly for dev usage with Preact-CLI, which needs those tags. 

If you want to prerender your widget / lib, you can use [`preact-render-to-string`](https://github.com/preactjs/preact-render-to-string) to output a string of HTML that you can then place inside your HTML file.
