### ISSUE TITLE
How to build for standalone use?

### ISSUE THREAD

**Issue by wei** [preactjs-templates/widget#18]
Hi there, thanks for the awesome project. I need some guidance on how to build the project for standalone use.

In a new project created with `npx preact-cli create widget my-widget`, I ran `npm run build:widget` and created an `index.html` at project root as follows (I'm including the script directly with `<script src="dist/index.umd.js"></script>`)

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<style>
			.preview {
				width: 100%;
				max-width: 1100px;
				margin: 80px auto;
				border: 1px dashed rgba(0, 0, 0, 0.2);
				position: relative;
			}

			.preview::before {
				content: 'WIDGET PREVIEW';
				position: absolute;
				display: block;
				top: -18px;
				font-size: 11px;
				color: rgba(0, 0, 0, 0.5);
			}
		</style>
	</head>
	<body>
		<div data-widget-host="habitat" class="preview">
			<script type="text/props">
			  { "color": "red"}
			</script>
		</div>
		<script src="dist/index.umd.js"></script>
	</body>
</html>
```

The browser console errors with:

![image](https://user-images.githubusercontent.com/5880908/123554835-fce22780-d74f-11eb-97c7-d9e6729d7e5b.png)

My goal is to be able to use the script directly on a web page with `data-widget-host` div, any advise is highly appreciated!

**Comment by rschristian** [comment]
Microbundle does not bundle devDependencies by default. You need to provide both `preact` and `preact-habitat` in your page or alter the build command to `"build:widget": "microbundle build --external none"`. This will ensure both dependencies are in your bundle, ready for drop-in use. This of course does mean you're importing both of these dependencies per-widget. If you have multiple widgets on the page built in this fashion, you're paying for these dependencies multiple times in your bundle size.

You can brows [Microbundle's options here](https://github.com/developit/microbundle/#all-cli-options-) in case you need some more configuration.

**Comment by wei** [comment]
I really appreciate your prompt and detailed response!
