### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by Soul244** [preactjs-templates/widget#19]
I tried every possible solution to run my widget in build but getting different errors.

My build command:     

"build:lib": "microbundle build -i src/index.js --external none",

I imported index.modern.js in a html file for test purpose and added requested html code to work with widget. Getting this error:

Importing code:

`    <script
      async
      type="module"
      src="./index.modern.js"
      type="text/javascript"
    ></script>`

Latest Error:
![Ekran Alıntısı](https://user-images.githubusercontent.com/20193416/128998686-fe67caf8-cca0-4d29-b03a-19ae1ab724c5.PNG)

Do you have any idea, how can i solve this problem?

**Comment by rschristian** [comment]
`process` is from Node. It doesn't exist as a global outside of it (assuming you don't provide a polyfill).

You can define vals with Microbundle like:

```
microbundle --define FOO=123,process.env.NODE="development"
```

**Comment by Soul244** [comment]
I am thankful for your answer but still getting the same error. 

I have changed build command with this:

`"build:lib": "microbundle --define process.env.NODE='production' --external none build -i src/index.js",`

I am trying to run build files in widget-test folder. This is my project:

https://codesandbox.io/s/muddy-fog-uthrc

**Comment by rschristian** [comment]
You should double check your error message.

The code is trying to use `process.env.NODE_ENV`, but you've set `process.env.NODE`. The define flag is simple string substitution; since `process.env.NODE` (as you wrote it) doesn't exist, nothing gets substituted.

**Comment by Soul244** [comment]
Finally it worked 🥳 thank you so much.
