### ISSUE TITLE
Description is null for widget in output of preact list

### ISSUE THREAD

**Issue by Download** [preactjs-templates/widget#3]
With the `list` command you can list all official templates, but currently it's output has `null` for the description of the `widget` template: 

```sh
$ preact list

i INFO Available official templates:

  ⭐️  default - The default `preact-cli` template.
  ⭐️  material - The material design `preact-cli` template.
  ⭐️  simple - Dead simple 'Hello world' template
  ⭐️  widget - null
```

I suspect that is because this Github repo currently says:

> No description, website, or topics provided.

Small issue but adds some polish if you fix it.

**Comment by reznord** [comment]
Need to add a description in the Github repo. That should fix this.

cc @zouhir
