### ISSUE TITLE
Question: Why is Webpack polyfill included?

### ISSUE THREAD

**Issue by Download** [preactjs-templates/widget#4]
Hi, in *index.js* in this template, on the first line, there is this import of a polyfill:

```js
let poly = require("preact-cli/lib/lib/webpack/polyfills");
```

Can you explain why this is needed? I thought Preact CLI already has a smart mechanism to load polyfills for `Promise` and `fetch`?

**Comment by elyalvarado** [comment]
In a regular preact-cli app, the polyfills are bundled in a different .js file which is conditionally loaded depending on the browser. However, in this template you most likely want to have only one JS file with all the code needed, that is why if you look at the `preact.config.js` file you'll see the following line which removes the preact-cli entry point for the polyfills.

```
delete config.entry.polyfills
```

Without that line you mention in the _index.js_ file the polyfills won't be included in your bundle.

**Comment by Download** [comment]
Thanks for clearing that up!
