### ISSUE TITLE
Does not work properly. Css classes being ignored

### ISSUE THREAD

**Issue by rafinskipg** [preactjs-templates/widget#7]
After trying this template and the simple one, i see that in this project CSS classes are being ignored. 

I wish i knew better what is the problem, because i really need to export a widget. And this project seemed really promising. But maybe it is  forgotten

**Comment by SimonKlausLudwig** [comment]
I have the same problem. Thanks for the awesome work. Would be great if CSS-classes would work.

**Comment by SimonKlausLudwig** [comment]
I've found a solution. Add this to your preact.config.js in your project where you want to use the library.

```
var cssLoader = helpers.getLoadersByName(config, 'css-loader')[0];
    cssLoader.rule.include.push('/Users/sl/Documents/projects/newbrnd/src/main/webapp/bestellkind/node_modules/preact-lazy-image');
    helpers.getLoadersByName(config, 'style-loader')[1].rule.exclude.push('/Users/sl/Documents/projects/newbrnd/src/main/webapp/bestellkind/node_modules/preact-lazy-image');
```

**Comment by slaat** [comment]
You have to import the style file and use them in your template like this:

`import style from './style.scss';`

`<p class={style.message_text}>{text}</p>`
